apps/courses/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'rapzhang'
__data__ = '2019/4/2 10:50'

from django.conf.urls import url
from .views import CourseListView,CourseDetailView,CourseInfoView,CommentsView,AddCommentView,VideoPlayView

urlpatterns = [
    #课程列表页
    url(r'^list/$',CourseListView.as_view(),name='course_list'),

    # 课程详情页
     url(r'^detail/course_id=(?P<course_id>\d+)$', CourseDetailView.as_view(), name='course_detail'),

    # 课程学习页面
    url(r'^info/course_id=(?P<course_id>\d+)$', CourseInfoView.as_view(), name='course_info'),

    # 课程评论页面
    url(r'^comment/course_id=(?P<course_id>\d+)$', CommentsView.as_view(), name='course_comment'),

    # 前端ajax访问的接口 - 添加用户评论
    url(r'^add_comment/$', AddCommentView.as_view(), name='add_comment'),

    # 视频的url匹配路径
    url(r'^video/video_id=(?P<video_id>\d+)$', VideoPlayView.as_view(), name='video_play'),

]

apps/organization/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'rapzhang'
__data__ = '2019/3/31 12:18'

from django.conf.urls import url
from .views import OrgView,AddUserAskView,OrgHomeView,OrgCourseView,OrgDescView,OrgTeacherView,AddFavView
from .views import TeacherView,TeacherDetailView

urlpatterns = [
    #课程机构列表页
    url(r'^list/$',OrgView.as_view(),name='org_list'),

    # 用户咨询
    url(r'^add_ask/$',AddUserAskView.as_view(),name='add_ask'),

    # 机构首页
    url(r'^home/(?P<org_id>\d+)$',OrgHomeView.as_view(),name='org_home'),

    # 机构课程列表页
    url(r'^course/(?P<org_id>\d+)$', OrgCourseView.as_view(), name='org_course'),

    # 课程机构介绍
    url(r'^desc/(?P<org_id>\d+)$', OrgDescView.as_view(), name='org_desc'),

    # 机构教师介绍
    url(r'^org_teacher/(?P<org_id>\d+)$', OrgTeacherView.as_view(), name='org_teacher'),

    # 收藏功能的统一调用API
    url(r'^add_fav/$',AddFavView.as_view(),name='add_fav'),

    # 讲师列表页面展示
    url(r'^teacher/$',TeacherView.as_view(),name='teacher'),

    # 讲师详情页
    url(r'^teacher_detail/teacher_id=(?P<teacher_id>\d+)$', TeacherDetailView.as_view(), name='teacher_detail'),

]

apps/users/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'rapzhang'
__data__ = '2019/4/5 23:11'

from django.conf.urls import url,include

from .views import UserInfoView,UploadImageView,UpdatePwdView,SendEmailCodeView,UpdateEmailView
from .views import MyCourseView,MyFavOrgView,MyFavTeacherView,MyFavCourseView,MyMessageView

urlpatterns = [
    # 用户个人中心信息
    url(r'^info/$',UserInfoView.as_view(),name="user_info"),

    # 用户头像上传修改
    url(r'^image/upload/$',UploadImageView.as_view(),name="image_upload"),

    # 用户个人中心修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name="update_pwd"),

    # 发送邮箱的数字验证码
    url(r'^sendEmail_code/$',SendEmailCodeView.as_view(), name="sendEmail_code"),

    # 验证邮箱的验证码是否和数据库一致
    url(r'^update_email/$', UpdateEmailView.as_view(), name="update_email"),

    # 个人中心我的课程页面
    url(r'^mycourse/$', MyCourseView.as_view(), name="mycourse"),

    # 收藏的课程机构
    url(r'^myfav/org/$', MyFavOrgView.as_view(), name="myfav_org"),

    # 收藏的教师
    url(r'^myfav/teacher/$', MyFavTeacherView.as_view(), name="myfav_teacher"),

    # 收藏的课程
    url(r'^myfav/course/$', MyFavCourseView.as_view(), name="myfav_course"),

    # 我的消息页面
    url(r'^myMessage$', MyMessageView.as_view(), name="myMessage"),

]

rapzhang_online/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView  # 此方法处理静态文件
import xadmin
import DjangoUeditor
from django.views.static import serve  # 处理静态文件（media)

from users.views import LoginView,RegisterView,ActiveUserView,ForgetPwdView,ResetView,ModifyPwdView,IndexView
from users.views import LoginUnsafaView
from organization.views import OrgView
from rapzhang_online.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),

    # url('^$',TemplateView.as_view(template_name='index.html'),name='index'),
    url(r'^$',IndexView.as_view(),name='index'),
    url('^login/$',LoginView.as_view(), name='login'),
    url('^logout/$',LoginView.as_view(), name='logout'),
    url('^captcha/',include('captcha.urls')),
    url('^register/$',RegisterView.as_view(),name='register'),
    url('^active/(?P<active_code>.*)/$',ActiveUserView.as_view(),name='user_active'),
    url('^forgetpwd/$',ForgetPwdView.as_view(),name='forget_pwd'),
    url('^reset/(?P<reset_code>.*)/$', ResetView.as_view(), name='reset_pwd'),
    url('^modify_pwd/$',ModifyPwdView.as_view(),name='modify_pwd'),

    # 课程机构url配置 (url分发)
    url('^org/', include('organization.urls',namespace='org')), # Include添加命名空间属性，避免class重名

    # 公开课页面(url分发)
    url('^course/', include('courses.urls', namespace='course')),  # Include添加命名空间属性，避免class重名

    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # 将debug改为True，django服务器自动不会寻找static目录渲染页面，需要我们自己配置
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),

    # 个人中心相关url配置
    url(r'^users/',include('users.urls',namespace='users')),

    # DjangoUeditor(富文本)
    url(r'^ueditor/',include('DjangoUeditor.urls' ))
]


# 配置全局的404,500页面
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/courses/models.py
from datetime import datetime

# Create your models here.
from django.db import models
from DjangoUeditor.models import UEditorField

from organization.models import CourseOrg,Teacher


# 课程详情页实体类
class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg,verbose_name='课程机构',null=True,blank=True)
    name = models.CharField(max_length=50,verbose_name=u'课程名称')
    desc = models.CharField(max_length=300,verbose_name=u'课程描述')
    detail =UEditorField(verbose_name=u'课程详情',width=1200, height=300, imagePath="course/ueditor/",
                                filePath="course/ueditor/",default='')
    degree = models.CharField(verbose_name='课程难度',choices=(('cj','初级'),('zj','中级'),('gj','高级')),max_length=2) # 课程难度
    learn_times = models.IntegerField(default=0,verbose_name=u'学习时长(分钟数)')
    students = models.IntegerField(default=0,verbose_name=u'学习人数')
    fav_nums = models.IntegerField(default=0,verbose_name=u'收藏人数')
    image = models.ImageField(upload_to="courses/%Y/%m",verbose_name=u'封面图',max_length=100,null=True,blank=True)
    tag = models.CharField(default='',verbose_name=u'课程标签',max_length=10)
    category = models.CharField(max_length=20,default=u'后端开发',verbose_name=u'课程类别')
    num_click = models.IntegerField(default=0,verbose_name='点击数')
    teacher = models.ForeignKey(Teacher,verbose_name=u'授课老师',null=True,blank=True)
    need_know = models.CharField(max_length=100,default='',null=True,blank=True,verbose_name=u'课程须知')
    teacher_all = models.CharField(max_length=100,default='',null=True,blank=True,verbose_name=u'老师告诉你')
    is_banner = models.BooleanField(default=False,verbose_name=u'是否轮播')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        # 获取课程章节数
        return self.lesson_set.all().count()
    get_zj_nums.short_description = '章节数'

    # 显示在xadmin后台页面进行跳转
    def go_to(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<a href='https://www.baidu.com'>跳转百度 </a>'")
    go_to.short_description = '跳转'

    def get_learn_user(self):
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        # 获取所有章节信息
        return self.lesson_set.all()

    def __str__(self):
        return self.name

class BannerCourse(Course):
     class Meta:
         verbose_name = '轮播课程'
         verbose_name_plural = verbose_name
         proxy = True



# 章节信息实体类
class Lesson(models.Model):
    # 一(course) 对 多(lesson) 关系,在多的实体类中添加外键
    course = models.ForeignKey(Course,verbose_name=u'课程')
    name = models.CharField(max_length=100,verbose_name=u'章节名')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


    #  通过外键获取章节的所有视频
    def get_lesson_video(self):
        return self.video_set.all()


# 视频播放地址实体类
class Video(models.Model):
    lesson = models.ForeignKey(Lesson,verbose_name=u'章节')
    url = models.CharField(max_length=200,default='',verbose_name=u'访问地址')
    name = models.CharField(max_length=100,verbose_name=u'视频名称')
    learn_times = models.IntegerField(default=0, verbose_name=u'学习时长(分钟数)')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name


# 课程资源
class CourseResource(models.Model):
    course = models.ForeignKey(Course,verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'资源名称')
    download = models.FileField(upload_to="course/resource/%Y/%m",verbose_name=u"资源文件",max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

templates/active_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>账号激活界面</title>
    <style>
        .content{
            width: 500px;
            height: 500px;
            {#border: 1px solid black;#}
            margin: 300px auto;
        }
        #center{
            {#border: 1px solid black;#}
            margin: 100px auto;
        }
    </style>
</head>
<body>

<div class="content">
    <div id="center">
        <h1> Success message! </h1>
        <h2>恭喜您成功激活您的账号</h2>
        <p>您的登陆名称为:<b>{{ email }}</b></p>
        <p>请牢记您的账号密码~~~~</p>
        <b><a color='red' href="{% url 'login' %}">回登陆页面 >></a></b>
    </div>
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Rapzhang在线教育平台{% endblock %}


<!-- 面包屑 -->
{% block custom_bread %}

{% endblock %}



{% block content %}
<div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% for banner in all_banners %}
                            <li>
                                    <a href="{{ banner.url }}">
                                        <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
                            {% endfor %}

						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="{% static 'images/feature1.png' %}"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="{% static 'images/feature2.png' %}"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="{% static 'images/feature3.png' %}"/>
					<p class="center">学生授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="{% static 'images/feature4.png' %}"/>
					<p class="center">测试数据</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                    {% for banner_course in banner_courses %}
                                    <li>
                                        <a href="{% url 'course:course_detail' banner_course.id %}">
                                            <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_course.image }}" />
                                        </a>
                                    </li>
                                    {% endfor %}

								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                            {% for course in courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="course-detail.html">
                                        <h2 title="django入门">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="慕课网">{{ course.course_org.name }}</span>
                                    <span class="star fr">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                            {% endfor %}

					</div>
				</div>
			</div>
		</div>
	</section>
<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="{% static 'images/module3_1.jpg' %}"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
                            {% for course_org in course_orgs %}
                                <li class="{% if forloop.counter|divisibleby:'5' %}five{% endif %}">
                                    <a href="{% url 'org:org_home' course_org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ course_org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ course_org.name }}">{{ course_org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}

						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}Rapzhang在线教育平台{% endblock %}</title>

	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}{% endblock %}

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
                <div class="top">
				<div class="wp">
					<div class="fl">
                        <p>联系方式：<b>17737778234</b></p>
                    </div>
                  <!--登录后跳转-->
                    {% if request.user.is_authenticated %}
                            <div class="personal">
                            <dl class="user fr">
                                <dd>{{ reqeust.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ request.user.username }}</h2>
	                                    <p>{{ request.user.email }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                            <a href="{% url 'users:myMessage' %}">
                            <div class="msg-num"><span id="MsgNum">{{ request.user.get_unread_nums }}</span></div>
                        </a>

                        {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                        {% endif %}

				</div>
			</div>


    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
            <div class="head fl">
                <h1>
                    {{ course_org.name }}
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="4.7"></span>
                    <span class="key">4.7</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 "data-favid="22" data-fav-type="1">
                 {% if not has_fav %}收藏{% else %}已收藏{% endif %}
            </div>

            </div>
        </div>
        </div>
    </header>
</section>

<!-- 面包选择器 -->
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
			<li>{% block page_path %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">机构讲师</a></li>
			</ul>
		</div>
        {% block right_form %}

        {% endblock %}

</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->

<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>

<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"/org/add_fav/",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="/login/";
                }else{
                   // alert(data.msg)
                    current_elem.text('收藏')

                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static 'images/' %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter_base.html' %}

{% load staticfiles %}


{% block title %}个人中心-Rapzhang在线教育平台{% endblock %}

{% block custom_bread %}
<section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="12"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter_base.html' %}

{% load staticfiles %}


{% block title %}个人中心-Rapzhang在线教育平台{% endblock %}

{% block custom_bread %}
<section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in org_list %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:org_home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.city }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
{% endblock %}